name: audit

on:
  pull_request:
    branches: [ master, develop ]

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        php: [7.3.0]

    steps:
    - uses: actions/checkout@v2

    - name: Run php tests
      uses: nathanheffley/laravel-phpunit-action@v0.1.0
